apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  selector:
    app: moodle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
---
# Moodle Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: docker.io/bitnami/moodle:4.3
        ports:
        - containerPort: 8080
          hostPort: 80
          protocol: TCP
        - containerPort: 443
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MOODLE_DATABASE_USER
          value: admin_apsico
        - name: MOODLE_DATABASE_HOST
          value: mariadb
        - name: MOODLE_DATABASE_PORT_NUMBER
          value: "3306"
        - name: MOODLE_DATABASE_TYPE
          value: mariadb
        - name: MOODLE_DATABASE_NAME
          value: apsico_moodle
        - name: MARIADB_USER
          value: admin_apsico
        - name: MARIADB_DATABASE
          value: apsico_moodle
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
        - name: moodledata-data
          mountPath: /bitnami/moodledata
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-data
      - name: moodledata-data
        persistentVolumeClaim:
          claimName: moodledata-data
