apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: moodle
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
--- 
# MariaDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: moodle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/mariadb']
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb-data
      containers:
      - name: mariadb
        image: docker.io/bitnami/mariadb:11.3
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        env:
        #--------------------------#
        - name: MARIADB_USER # Must be the same as MOODLE_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD # Must be the same as MOODLE_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_PASSWORD
        #--------------------------#
        - name: MARIADB_ROOT_USER
          valueFrom: 
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_ROOT_USER 
        - name: MARIADB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_ROOT_PASSWORD
        #--------------------------#
        - name: MARIADB_SKIP_TEST_DB
          value: "yes"
        - name: MARIADB_ENABLE_SLOW_QUERY
          value: "1"
        - name: MARIADB_LONG_QUERY_TIME
          value: "2"
        - name: MARIADB_DATABASE
          valueFrom: 
            secretKeyRef:
              name: mariadb-secret
              key: MARIA_DATABASE_NAME
        - name: MARIADB_CHARACTER_SET
          value: utf8mb4
        - name: MARIADB_COLLATE
          value: utf8mb4_unicode_ci
        volumeMounts:
        - name: mariadb-data
          mountPath: /bitnami/mariadb
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
