apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
--- 
# MariaDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 1001:1001 /bitnami/mariadb']
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb-data
      containers:
      - name: mariadb
        image: docker.io/bitnami/mariadb:11.3
        securityContext:
          runAsUser: 1001
        ports:
        - containerPort: 3306
        #resources:
          #limits:
          #  cpu: 500m
          #  ephemeral-storage: 1Gi
          #  memory: 2Gi
          #requests:
          #  cpu: 500m
          #  ephemeral-storage: 1Gi
          #  memory: 2Gi
        env:
        #--------------------------#
        - name: MARIADB_USER # Must be the same as MOODLE_DATABASE_USER
          value: apsico_user_mariadb
        - name: MARIADB_PASSWORD # Must be the same as MOODLE_DATABASE_PASSWORD
          value: "2222" # Test. Pasar a secret
        #--------------------------#
        - name: MARIADB_ROOT_USER
          value: admin_apsico_db_root
        - name: MARIADB_ROOT_PASSWORD
          value: "1234" # Test. Pasar a secret
        #--------------------------#
        - name: MARIADB_SKIP_TEST_DB
          value: "yes"
        - name: MARIADB_ENABLE_SLOW_QUERY
          value: "1"
        - name: MARIADB_LONG_QUERY_TIME
          value: "2"
        - name: MARIADB_DATABASE
          value: apsico_moodle
        - name: MARIADB_CHARACTER_SET
          value: utf8mb4
        - name: MARIADB_COLLATE
          value: utf8mb4_unicode_ci
        volumeMounts:
        - name: mariadb-data
          mountPath: /bitnami/mariadb
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
