apiVersion: v1
kind: Service
metadata:
  name: moodle-svc
  namespace: moodle
spec:
  selector:
    app: moodle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Moodle Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deploy
  namespace: moodle
spec:
  replicas: 1
  #strategy:
  #  type: RollingUpdate
  #  rollingUpdate:
  #    maxUnavailable: 0
  #    maxSurge: 0
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: docker.io/bitnami/moodle:4.3
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        #--------------------------------------------------#  
        - name: MOODLE_DATABASE_USER # Must be the same as MARIADB_USER
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_USER 
        - name: MOODLE_DATABASE_PASSWORD # Must be the same as MARIADB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_PASSWORD 
        #--------------------------------------------------#
        - name: MOODLE_DATABASE_HOST
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_HOST
        - name: MOODLE_DATABASE_TYPE
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_TYPE
        - name: MOODLE_DATABASE_NAME
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_DATABASE_NAME
        #----------- Moodle admin credentials --------------#
        - name: MOODLE_USERNAME 
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_USERNAME
        - name: MOODLE_PASSWORD 
          valueFrom: 
            secretKeyRef:
              name: moodle-secret
              key: MOODLE_PASSWORD
        #--------------------------------------------------#
        - name: EXTRA_LOCALES
          value: es_ES.UTF-8 UTF-8
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
        - name: moodledata-file
          mountPath: /bitnami/moodledatafile
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-data-pvc
      - name: moodledata-file
        persistentVolumeClaim:
          claimName: moodledata-file-pvc
