apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  selector:
    app: moodle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
# Moodle Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: docker.io/bitnami/moodle:4.3
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        #--------------------------------------------------#  
        - name: MOODLE_DATABASE_USER # Must be the same as MARIADB_USER
          value: apsico_user_mariadb
        - name: MOODLE_DATABASE_PASSWORD # Must be the same as MARIADB_PASSWORD
          value: "2222" # Test. Pasar a secret
        #--------------------------------------------------#
        - name: MOODLE_DATABASE_HOST
          value: mariadb
        - name: MOODLE_DATABASE_TYPE
          value: mariadb
        - name: MOODLE_DATABASE_NAME
          value: apsico_moodle
        #----------- Moodle admin credentials --------------#
        - name: MOODLE_USERNAME # Test. Pasar a secret
          value: admin_apsico_moodle # Test. Pasar a secret
        - name: MOODLE_PASSWORD # Test. Pasar a secret
          value: "1111" # Test. Pasar a secret
        #--------------------------------------------------#
        - name: EXTRA_LOCALES
          value: es_ES.UTF-8 UTF-8
        volumeMounts:
        - name: moodle-data
          mountPath: /bitnami/moodle
        - name: moodledata-data
          mountPath: /bitnami/moodledata
      volumes:
      - name: moodle-data
        persistentVolumeClaim:
          claimName: moodle-data
      - name: moodledata-data
        persistentVolumeClaim:
          claimName: moodledata-data
