apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: moodle-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodledata-data
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: moodle-storage-class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mariadb-storage-class
