apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: moodle-vpa
  namespace: moodle
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       moodle
  updatePolicy:
    updateMode: "Auto"
