version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    ports:
      - '3306:9000'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # only for development
      - MARIADB_USER=admin-apsico
      - MARIADB_DATABASE=apsico_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MARIADB_USER=admin-apsico
      - MARIADB_DATABASE=apsico_moodle
      - ALLOW_EMPTY_PASSWORD=yes # only for development
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
