apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.pv.name }}
spec:
    capacity:
        storage: {{ .Values.pv.storage }}
    accessModes:
        - {{ .Values.pv.accessModes }}
    persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}
    storageClassName: {{ .Values.storageClass.name }}
    #hostPath:
    #    path: {{ .Values.pv.path }}
    gcePersistentDisk:
        pdName: {{ .Values.pv.name }}
        fsType: {{ .Values.storageClass.parameters.fstype }}
        readOnly: false
        volumeMode: Filesystem