apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
  volumeName: {{ .Values.pv.name }}
  storageClassName: {{ .Values.storageClass.name}}
  volumeName: {{ .Values.pv.name }}