apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: docker.io/bitnami/mariadb:11.2
        ports:
        - containerPort: 3306
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_USER
          value: admin-apsico
        - name: MARIADB_DATABASE
          value: apsico_moodle
        - name: MARIADB_CHARACTER_SET
          value: utf8mb4
        - name: MARIADB_COLLATE
          value: utf8mb4_unicode_ci
        volumeMounts:
        - name: mariadb-data
          mountPath: /bitnami/mariadb
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
