apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort1 }}
        - containerPort: {{ .Values.deployment.containerPort2 }}
        resources:
          limits:
            cpu: {{ .Values.deployment.resources.limits.cpu }}
            memory: {{ .Values.deployment.resources.limits.memory }}
          requests:
            cpu: {{ .Values.deployment.resources.requests.cpu }}
            memory: {{ .Values.deployment.resources.requests.memory }}
        env:
        - name: MOODLE_DATABASE_USER
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_DATABASE_USER
        - name: MOODLE_DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_DATABASE_PASSWORD
        - name: MOODLE_DATABASE_HOST
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_DATABASE_HOST
        - name: MOODLE_DATABASE_TYPE
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_DATABASE_TYPE
        - name: MOODLE_DATABASE_NAME
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_DATABASE_NAME
        - name: MOODLE_USERNAME
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_USERNAME
        - name: MOODLE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: MOODLE_PASSWORD
        volumeMounts:
        - name: {{ .Values.deployment.volumeMounts.data.name }}
          mountPath: {{ .Values.deployment.volumeMounts.data.mountPath }}
        - name: {{ .Values.deployment.volumeMounts.files.name }}
          mountPath: {{ .Values.deployment.volumeMounts.files.mountPath }}
      volumes:
      - name: {{ .Values.deployment.volumes.data.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.moodledata.name }}
      - name: {{ .Values.deployment.volumes.files.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.moodledatafile.name }}
