apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.pv.moodledata.name }}
    namespace: {{ .Values.namespace.name }}
spec:
    capacity:
        storage: {{ .Values.pv.moodledata.storage }}
    accessModes:
        - {{ .Values.pv.moodledata.accessModes }}
    persistentVolumeReclaimPolicy: {{ .Values.pv.moodledata.reclaimPolicy }}
    storageClassName: {{ .Values.storageClass.name }}
    gcePersistentDisk:
        pdName: {{ .Values.pv.moodledata.name }}
        fsType: {{ .Values.storageClass.parameters.fstype }}
        readOnly: false
        volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.pv.moodledatafile.name }}
    namespace: {{ .Values.namespace.name }}
spec:
    capacity:
        storage: {{ .Values.pv.moodledatafile.storage }}
    accessModes:
        - {{ .Values.pv.moodledatafile.accessModes }}
    persistentVolumeReclaimPolicy: {{ .Values.pv.moodledatafile.reclaimPolicy }}
    storageClassName: {{ .Values.storageClass.name }}
    gcePersistentDisk:
        pdName: {{ .Values.pv.moodledatafile.name }}
        fsType: {{ .Values.storageClass.parameters.fstype }}
        readOnly: false
        volumeMode: Filesystem