apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.moodledata.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.pvc.moodledata.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.moodledata.storage }}
  storageClassName: {{ .Values.storageClass.name }}
  volumeName: {{ .Values.pv.moodledata.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.moodledatafile.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
    - {{ .Values.pvc.moodledatafile.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.moodledatafile.storage }}
  storageClassName: {{ .Values.storageClass.name }}
  volumeName: {{ .Values.pv.moodledatafile.name }}