namespace: 
  name: moodle
service:
  name: moodle-svc
  type: LoadBalancer
  protocol: TCP
  port: 80
  targetPort: 80
app:
  name: moodle
secret:
  name: moodle-secret
deployment:
  name: moodle-deployment
  replicas: 1
  image: docker.io/bitnami/moodle
  tag: latest
  containerPort1: 80
  containerPort2: 443
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  volumeMounts:
    data: 
      name: moodle-data
      mountPath: /bitnami/moodle
    files:
      name: moodledata-file
      mountPath: /bitnami/moodledata
  volumes:
    data:
      name: moodle-data
    files:
      name: moodledata-file
pvc:
  moodledata:
    name: moodle-data-pvc 
    accessModes: ReadWriteOnce
    storage: 10Gi
  moodledatafile:
    name: moodledata-file-pvc
    accessModes: ReadWriteOnce
    storage: 10Gi
storageClass:
  name: moodle-storage-class
  provisioner: kubernetes.io/gce-pd
  parameters:
    type: pd-standard
    fstype: ext4
  reclaimPolicy: Delete # delete for testing purposes. Change to Retain for production
  allowVolumeExpansion: true
